import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class TwelveMiltiSeventy extends StatelessWidget {
  const TwelveMiltiSeventy({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('12/70'),
        centerTitle: true,
        backgroundColor: Colors.green,
      ),
      body: ListView(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              SizedBox(height: 150,),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: const [
                  SizedBox(height: 20,),
                  Text('НАЗВАНИЕ:', style: TextStyle(fontSize: 18),),
                  SizedBox(height: 15,),
                  Text('12/70 "AP-20"'),
                  SizedBox(height: 15,),
                  Text('12/70 флешетта'),
                  SizedBox(height: 15,),
                  Text('12/70 пуля кустарная .50 BMG'),
                  SizedBox(height: 15,),
                  Text('12/70 пуля "Полева-6у"'),
                  SizedBox(height: 15,),
                  Text('12/70 пуля "FTX Custom Lite"'),
                  SizedBox(height: 15,),
                  Text('12/70 пуля "Полева-3"'),
                  SizedBox(height: 15,),
                  Text('12/70 "Dual Sabot"'),
                  SizedBox(height: 15,),
                  Text('12/70 свинцовая пуля'),
                  SizedBox(height: 15,),
                  Text('12/70 "Copper Sabot Premier"'),
                  SizedBox(height: 15,),
                  Text('12/70 пуля "Гризли 40"'),
                  SizedBox(height: 15,),
                  Text('12/70 "SuperFormance"'),
                  SizedBox(height: 15,),
                  Text('12/70 6.5мм "Экспресс"'),
                  SizedBox(height: 15,),
                  Text('12/70 7мм картечь'),
                  SizedBox(height: 15,),
                  Text('12/70 RIP'),
                  SizedBox(height: 15,),
                  Text('12/70 8.5мм картечь "Магнум"'),
                  SizedBox(height: 15,),
                  Text('12/70 5.25мм картечь'),
                ],
              ),
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: const [
                  SizedBox(height: 20,),
                  Text('УРОН:', style: TextStyle(fontSize: 18)),
                  SizedBox(height: 15,),
                  Text('164'),
                  SizedBox(height: 15,),
                  Text('25'),
                  SizedBox(height: 15,),
                  Text('197'),
                  SizedBox(height: 15,),
                  Text('150'),
                  SizedBox(height: 15,),
                  Text('183'),
                  SizedBox(height: 15,),
                  Text('140'),
                  SizedBox(height: 15,),
                  Text('185'),
                  SizedBox(height: 15,),
                  Text('167'),
                  SizedBox(height: 15,),
                  Text('206'),
                  SizedBox(height: 15,),
                  Text('190'),
                  SizedBox(height: 15,),
                  Text('220'),
                  SizedBox(height: 15,),
                  Text('35'),
                  SizedBox(height: 15,),
                  Text('39'),
                  SizedBox(height: 15,),
                  Text('265'),
                  SizedBox(height: 15,),
                  Text('50'),
                  SizedBox(height: 15,),
                  Text('37'),
                ],
              ),
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: const [
                  SizedBox(height: 20,),
                  Text('ПО БРОНЕ:', style: TextStyle(fontSize: 18)),
                  SizedBox(height: 15,),
                  Text('65'),
                  SizedBox(height: 15,),
                  Text('26'),
                  SizedBox(height: 15,),
                  Text('57'),
                  SizedBox(height: 15,),
                  Text('50'),
                  SizedBox(height: 15,),
                  Text('50'),
                  SizedBox(height: 15,),
                  Text('40'),
                  SizedBox(height: 15,),
                  Text('65'),
                  SizedBox(height: 15,),
                  Text('55'),
                  SizedBox(height: 15,),
                  Text('46'),
                  SizedBox(height: 15,),
                  Text('48'),
                  SizedBox(height: 15,),
                  Text('12'),
                  SizedBox(height: 15,),
                  Text('26'),
                  SizedBox(height: 15,),
                  Text('26'),
                  SizedBox(height: 15,),
                  Text('11'),
                  SizedBox(height: 15,),
                  Text('26'),
                  SizedBox(height: 15,),
                  Text('15'),
                ],
              ),
              Column(
                mainAxisAlignment: MainAxisAlignment.start,
                children: const [
                  SizedBox(height: 20,),
                  Text('КЛАСС:', style: TextStyle(fontSize: 18)),
                  SizedBox(height: 15,),
                  Text('3 и 70% 4'),
                  SizedBox(height: 15,),
                  Text('3 и 10% 4'),
                  SizedBox(height: 15,),
                  Text('2 и 60% 3'),
                  SizedBox(height: 15,),
                  Text('2'),
                  SizedBox(height: 15,),
                  Text('2'),
                  SizedBox(height: 15,),
                  Text('1 и 70% 2'),
                  SizedBox(height: 15,),
                  Text('1 и 70% 2'),
                  SizedBox(height: 15,),
                  Text('1 и 50% 2'),
                  SizedBox(height: 15,),
                  Text('1 и 40% 2'),
                  SizedBox(height: 15,),
                  Text('1 и 20% 2'),
                  SizedBox(height: 15,),
                  Text('0 и 50% 1'),
                  SizedBox(height: 15,),
                  Text('0 и 30% 1'),
                  SizedBox(height: 15,),
                  Text('0 и 30% 1'),
                  SizedBox(height: 15,),
                  Text('0 и 20% 1'),
                  SizedBox(height: 15,),
                  Text('0 и 20% 1'),
                  SizedBox(height: 15,),
                  Text('0 и 10% 1'),
                ],
              )
            ],
          )
        ],
      ),
    );
  }
}
